services:
  - type: web
    name: neptun
    env: python
    region: frankfurt
    plan: free
    runtime: "python3.9"
    buildCommand: |
      python -m pip install pip==23.3.2
      python -m pip install setuptools==69.0.3 wheel==0.42.0
      python -m pip install --no-cache-dir -r requirements.txt
      python -m spacy download en_core_web_sm
      python -m spacy download uk_core_news_sm
    startCommand: gunicorn wsgi:app --config gunicorn_config.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: "3.9.18"
      - key: PIP_DEFAULT_TIMEOUT
        value: "300"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: LANG
        value: "uk_UA.UTF-8"
      - key: TZ
        value: "Europe/Kiev"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
